version: '2'
services:
    master:
        image: quay.io/honestbee/locust
        environment:
            - "LOCUST_MODE=master"
            - "TARGET_HOST=http://site.example.com"
            - "LOCUST_SCRIPT=/locust-tasks/tasks_elb.py"
        volumes:
            - ./locust-image/app/locust-tasks/tasks_elb.py:/locust-tasks/tasks_elb.py
        networks:
            locust-nw:
        ports:
            - "8089:8089"
    worker:
        image: quay.io/honestbee/locust
        environment:
            - "LOCUST_MODE=worker"
            - "LOCUST_MASTER=master"
            - "LOCUST_MASTER_WEB=8089"
            - "TARGET_HOST=http://site.example.com"
            - "LOCUST_SCRIPT=/locust-tasks/tasks_elb.py"
        volumes:
            - ./locust-image/app/locust-tasks/tasks_elb.py:/locust-tasks/tasks_elb.py
        networks:
            locust-nw:

    # seeder:
    #     image: quay.io/locust-seeder:1.0.5
    #     networks:
    #         locust-nw:
    #             aliases:
    #                 - locust-seeder
    #     expose:
    #         - 5000

networks:
    locust-nw:
